/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedUserRouteRouteImport } from './routes/(protected)/user/route'
import { Route as protectedAdminRouteRouteImport } from './routes/(protected)/admin/route'
import { Route as protectedUserProfileIndexRouteImport } from './routes/(protected)/user/profile/index'
import { Route as protectedUserLoansIndexRouteImport } from './routes/(protected)/user/loans/index'
import { Route as protectedUserBooksIndexRouteImport } from './routes/(protected)/user/books/index'
import { Route as protectedAdminLoansIndexRouteImport } from './routes/(protected)/admin/loans/index'
import { Route as protectedAdminBooksIndexRouteImport } from './routes/(protected)/admin/books/index'
import { Route as protectedAdminAuthorsIndexRouteImport } from './routes/(protected)/admin/authors/index'
import { Route as protectedUserBooksBookIdIndexRouteImport } from './routes/(protected)/user/books/$bookId/index'
import { Route as protectedAdminBooksAddIndexRouteImport } from './routes/(protected)/admin/books/add/index'
import { Route as protectedAdminBooksBookIdIndexRouteImport } from './routes/(protected)/admin/books/$bookId/index'
import { Route as protectedAdminAuthorsAddIndexRouteImport } from './routes/(protected)/admin/authors/add/index'
import { Route as protectedAdminAuthorsAuthorIdIndexRouteImport } from './routes/(protected)/admin/authors/$authorId/index'
import { Route as protectedAdminBooksBookIdEditIndexRouteImport } from './routes/(protected)/admin/books/$bookId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedUserRouteRoute = protectedUserRouteRouteImport.update({
  id: '/(protected)/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAdminRouteRoute = protectedAdminRouteRouteImport.update({
  id: '/(protected)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedUserProfileIndexRoute =
  protectedUserProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => protectedUserRouteRoute,
  } as any)
const protectedUserLoansIndexRoute = protectedUserLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => protectedUserRouteRoute,
} as any)
const protectedUserBooksIndexRoute = protectedUserBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => protectedUserRouteRoute,
} as any)
const protectedAdminLoansIndexRoute =
  protectedAdminLoansIndexRouteImport.update({
    id: '/loans/',
    path: '/loans/',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedAdminBooksIndexRoute =
  protectedAdminBooksIndexRouteImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedAdminAuthorsIndexRoute =
  protectedAdminAuthorsIndexRouteImport.update({
    id: '/authors/',
    path: '/authors/',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedUserBooksBookIdIndexRoute =
  protectedUserBooksBookIdIndexRouteImport.update({
    id: '/books/$bookId/',
    path: '/books/$bookId/',
    getParentRoute: () => protectedUserRouteRoute,
  } as any)
const protectedAdminBooksAddIndexRoute =
  protectedAdminBooksAddIndexRouteImport.update({
    id: '/books/add/',
    path: '/books/add/',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedAdminBooksBookIdIndexRoute =
  protectedAdminBooksBookIdIndexRouteImport.update({
    id: '/books/$bookId/',
    path: '/books/$bookId/',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedAdminAuthorsAddIndexRoute =
  protectedAdminAuthorsAddIndexRouteImport.update({
    id: '/authors/add/',
    path: '/authors/add/',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedAdminAuthorsAuthorIdIndexRoute =
  protectedAdminAuthorsAuthorIdIndexRouteImport.update({
    id: '/authors/$authorId/',
    path: '/authors/$authorId/',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedAdminBooksBookIdEditIndexRoute =
  protectedAdminBooksBookIdEditIndexRouteImport.update({
    id: '/books/$bookId/edit/',
    path: '/books/$bookId/edit/',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof protectedAdminRouteRouteWithChildren
  '/user': typeof protectedUserRouteRouteWithChildren
  '/admin/authors': typeof protectedAdminAuthorsIndexRoute
  '/admin/books': typeof protectedAdminBooksIndexRoute
  '/admin/loans': typeof protectedAdminLoansIndexRoute
  '/user/books': typeof protectedUserBooksIndexRoute
  '/user/loans': typeof protectedUserLoansIndexRoute
  '/user/profile': typeof protectedUserProfileIndexRoute
  '/admin/authors/$authorId': typeof protectedAdminAuthorsAuthorIdIndexRoute
  '/admin/authors/add': typeof protectedAdminAuthorsAddIndexRoute
  '/admin/books/$bookId': typeof protectedAdminBooksBookIdIndexRoute
  '/admin/books/add': typeof protectedAdminBooksAddIndexRoute
  '/user/books/$bookId': typeof protectedUserBooksBookIdIndexRoute
  '/admin/books/$bookId/edit': typeof protectedAdminBooksBookIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof protectedAdminRouteRouteWithChildren
  '/user': typeof protectedUserRouteRouteWithChildren
  '/admin/authors': typeof protectedAdminAuthorsIndexRoute
  '/admin/books': typeof protectedAdminBooksIndexRoute
  '/admin/loans': typeof protectedAdminLoansIndexRoute
  '/user/books': typeof protectedUserBooksIndexRoute
  '/user/loans': typeof protectedUserLoansIndexRoute
  '/user/profile': typeof protectedUserProfileIndexRoute
  '/admin/authors/$authorId': typeof protectedAdminAuthorsAuthorIdIndexRoute
  '/admin/authors/add': typeof protectedAdminAuthorsAddIndexRoute
  '/admin/books/$bookId': typeof protectedAdminBooksBookIdIndexRoute
  '/admin/books/add': typeof protectedAdminBooksAddIndexRoute
  '/user/books/$bookId': typeof protectedUserBooksBookIdIndexRoute
  '/admin/books/$bookId/edit': typeof protectedAdminBooksBookIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)/admin': typeof protectedAdminRouteRouteWithChildren
  '/(protected)/user': typeof protectedUserRouteRouteWithChildren
  '/(protected)/admin/authors/': typeof protectedAdminAuthorsIndexRoute
  '/(protected)/admin/books/': typeof protectedAdminBooksIndexRoute
  '/(protected)/admin/loans/': typeof protectedAdminLoansIndexRoute
  '/(protected)/user/books/': typeof protectedUserBooksIndexRoute
  '/(protected)/user/loans/': typeof protectedUserLoansIndexRoute
  '/(protected)/user/profile/': typeof protectedUserProfileIndexRoute
  '/(protected)/admin/authors/$authorId/': typeof protectedAdminAuthorsAuthorIdIndexRoute
  '/(protected)/admin/authors/add/': typeof protectedAdminAuthorsAddIndexRoute
  '/(protected)/admin/books/$bookId/': typeof protectedAdminBooksBookIdIndexRoute
  '/(protected)/admin/books/add/': typeof protectedAdminBooksAddIndexRoute
  '/(protected)/user/books/$bookId/': typeof protectedUserBooksBookIdIndexRoute
  '/(protected)/admin/books/$bookId/edit/': typeof protectedAdminBooksBookIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/user'
    | '/admin/authors'
    | '/admin/books'
    | '/admin/loans'
    | '/user/books'
    | '/user/loans'
    | '/user/profile'
    | '/admin/authors/$authorId'
    | '/admin/authors/add'
    | '/admin/books/$bookId'
    | '/admin/books/add'
    | '/user/books/$bookId'
    | '/admin/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/user'
    | '/admin/authors'
    | '/admin/books'
    | '/admin/loans'
    | '/user/books'
    | '/user/loans'
    | '/user/profile'
    | '/admin/authors/$authorId'
    | '/admin/authors/add'
    | '/admin/books/$bookId'
    | '/admin/books/add'
    | '/user/books/$bookId'
    | '/admin/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/(protected)/admin'
    | '/(protected)/user'
    | '/(protected)/admin/authors/'
    | '/(protected)/admin/books/'
    | '/(protected)/admin/loans/'
    | '/(protected)/user/books/'
    | '/(protected)/user/loans/'
    | '/(protected)/user/profile/'
    | '/(protected)/admin/authors/$authorId/'
    | '/(protected)/admin/authors/add/'
    | '/(protected)/admin/books/$bookId/'
    | '/(protected)/admin/books/add/'
    | '/(protected)/user/books/$bookId/'
    | '/(protected)/admin/books/$bookId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedAdminRouteRoute: typeof protectedAdminRouteRouteWithChildren
  protectedUserRouteRoute: typeof protectedUserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/user': {
      id: '/(protected)/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof protectedUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/admin': {
      id: '/(protected)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof protectedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/user/profile/': {
      id: '/(protected)/user/profile/'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof protectedUserProfileIndexRouteImport
      parentRoute: typeof protectedUserRouteRoute
    }
    '/(protected)/user/loans/': {
      id: '/(protected)/user/loans/'
      path: '/loans'
      fullPath: '/user/loans'
      preLoaderRoute: typeof protectedUserLoansIndexRouteImport
      parentRoute: typeof protectedUserRouteRoute
    }
    '/(protected)/user/books/': {
      id: '/(protected)/user/books/'
      path: '/books'
      fullPath: '/user/books'
      preLoaderRoute: typeof protectedUserBooksIndexRouteImport
      parentRoute: typeof protectedUserRouteRoute
    }
    '/(protected)/admin/loans/': {
      id: '/(protected)/admin/loans/'
      path: '/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof protectedAdminLoansIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/books/': {
      id: '/(protected)/admin/books/'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof protectedAdminBooksIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/authors/': {
      id: '/(protected)/admin/authors/'
      path: '/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof protectedAdminAuthorsIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/user/books/$bookId/': {
      id: '/(protected)/user/books/$bookId/'
      path: '/books/$bookId'
      fullPath: '/user/books/$bookId'
      preLoaderRoute: typeof protectedUserBooksBookIdIndexRouteImport
      parentRoute: typeof protectedUserRouteRoute
    }
    '/(protected)/admin/books/add/': {
      id: '/(protected)/admin/books/add/'
      path: '/books/add'
      fullPath: '/admin/books/add'
      preLoaderRoute: typeof protectedAdminBooksAddIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/books/$bookId/': {
      id: '/(protected)/admin/books/$bookId/'
      path: '/books/$bookId'
      fullPath: '/admin/books/$bookId'
      preLoaderRoute: typeof protectedAdminBooksBookIdIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/authors/add/': {
      id: '/(protected)/admin/authors/add/'
      path: '/authors/add'
      fullPath: '/admin/authors/add'
      preLoaderRoute: typeof protectedAdminAuthorsAddIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/authors/$authorId/': {
      id: '/(protected)/admin/authors/$authorId/'
      path: '/authors/$authorId'
      fullPath: '/admin/authors/$authorId'
      preLoaderRoute: typeof protectedAdminAuthorsAuthorIdIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/books/$bookId/edit/': {
      id: '/(protected)/admin/books/$bookId/edit/'
      path: '/books/$bookId/edit'
      fullPath: '/admin/books/$bookId/edit'
      preLoaderRoute: typeof protectedAdminBooksBookIdEditIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
  }
}

interface protectedAdminRouteRouteChildren {
  protectedAdminAuthorsIndexRoute: typeof protectedAdminAuthorsIndexRoute
  protectedAdminBooksIndexRoute: typeof protectedAdminBooksIndexRoute
  protectedAdminLoansIndexRoute: typeof protectedAdminLoansIndexRoute
  protectedAdminAuthorsAuthorIdIndexRoute: typeof protectedAdminAuthorsAuthorIdIndexRoute
  protectedAdminAuthorsAddIndexRoute: typeof protectedAdminAuthorsAddIndexRoute
  protectedAdminBooksBookIdIndexRoute: typeof protectedAdminBooksBookIdIndexRoute
  protectedAdminBooksAddIndexRoute: typeof protectedAdminBooksAddIndexRoute
  protectedAdminBooksBookIdEditIndexRoute: typeof protectedAdminBooksBookIdEditIndexRoute
}

const protectedAdminRouteRouteChildren: protectedAdminRouteRouteChildren = {
  protectedAdminAuthorsIndexRoute: protectedAdminAuthorsIndexRoute,
  protectedAdminBooksIndexRoute: protectedAdminBooksIndexRoute,
  protectedAdminLoansIndexRoute: protectedAdminLoansIndexRoute,
  protectedAdminAuthorsAuthorIdIndexRoute:
    protectedAdminAuthorsAuthorIdIndexRoute,
  protectedAdminAuthorsAddIndexRoute: protectedAdminAuthorsAddIndexRoute,
  protectedAdminBooksBookIdIndexRoute: protectedAdminBooksBookIdIndexRoute,
  protectedAdminBooksAddIndexRoute: protectedAdminBooksAddIndexRoute,
  protectedAdminBooksBookIdEditIndexRoute:
    protectedAdminBooksBookIdEditIndexRoute,
}

const protectedAdminRouteRouteWithChildren =
  protectedAdminRouteRoute._addFileChildren(protectedAdminRouteRouteChildren)

interface protectedUserRouteRouteChildren {
  protectedUserBooksIndexRoute: typeof protectedUserBooksIndexRoute
  protectedUserLoansIndexRoute: typeof protectedUserLoansIndexRoute
  protectedUserProfileIndexRoute: typeof protectedUserProfileIndexRoute
  protectedUserBooksBookIdIndexRoute: typeof protectedUserBooksBookIdIndexRoute
}

const protectedUserRouteRouteChildren: protectedUserRouteRouteChildren = {
  protectedUserBooksIndexRoute: protectedUserBooksIndexRoute,
  protectedUserLoansIndexRoute: protectedUserLoansIndexRoute,
  protectedUserProfileIndexRoute: protectedUserProfileIndexRoute,
  protectedUserBooksBookIdIndexRoute: protectedUserBooksBookIdIndexRoute,
}

const protectedUserRouteRouteWithChildren =
  protectedUserRouteRoute._addFileChildren(protectedUserRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedAdminRouteRoute: protectedAdminRouteRouteWithChildren,
  protectedUserRouteRoute: protectedUserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
