/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedUserRouteRouteImport } from './routes/(protected)/user/route'
import { Route as protectedAdminRouteRouteImport } from './routes/(protected)/admin/route'
import { Route as protectedAdminIndexRouteImport } from './routes/(protected)/admin/index'
import { Route as protectedUserProfileIndexRouteImport } from './routes/(protected)/user/profile/index'
import { Route as protectedUserLoansIndexRouteImport } from './routes/(protected)/user/loans/index'
import { Route as protectedUserBooksIndexRouteImport } from './routes/(protected)/user/books/index'
import { Route as protectedUserBooksBookIdIndexRouteImport } from './routes/(protected)/user/books/$bookId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedUserRouteRoute = protectedUserRouteRouteImport.update({
  id: '/(protected)/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAdminRouteRoute = protectedAdminRouteRouteImport.update({
  id: '/(protected)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAdminIndexRoute = protectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const protectedUserProfileIndexRoute =
  protectedUserProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => protectedUserRouteRoute,
  } as any)
const protectedUserLoansIndexRoute = protectedUserLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => protectedUserRouteRoute,
} as any)
const protectedUserBooksIndexRoute = protectedUserBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => protectedUserRouteRoute,
} as any)
const protectedUserBooksBookIdIndexRoute =
  protectedUserBooksBookIdIndexRouteImport.update({
    id: '/books/$bookId/',
    path: '/books/$bookId/',
    getParentRoute: () => protectedUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof protectedAdminRouteRouteWithChildren
  '/user': typeof protectedUserRouteRouteWithChildren
  '/admin/': typeof protectedAdminIndexRoute
  '/user/books': typeof protectedUserBooksIndexRoute
  '/user/loans': typeof protectedUserLoansIndexRoute
  '/user/profile': typeof protectedUserProfileIndexRoute
  '/user/books/$bookId': typeof protectedUserBooksBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user': typeof protectedUserRouteRouteWithChildren
  '/admin': typeof protectedAdminIndexRoute
  '/user/books': typeof protectedUserBooksIndexRoute
  '/user/loans': typeof protectedUserLoansIndexRoute
  '/user/profile': typeof protectedUserProfileIndexRoute
  '/user/books/$bookId': typeof protectedUserBooksBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)/admin': typeof protectedAdminRouteRouteWithChildren
  '/(protected)/user': typeof protectedUserRouteRouteWithChildren
  '/(protected)/admin/': typeof protectedAdminIndexRoute
  '/(protected)/user/books/': typeof protectedUserBooksIndexRoute
  '/(protected)/user/loans/': typeof protectedUserLoansIndexRoute
  '/(protected)/user/profile/': typeof protectedUserProfileIndexRoute
  '/(protected)/user/books/$bookId/': typeof protectedUserBooksBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/user'
    | '/admin/'
    | '/user/books'
    | '/user/loans'
    | '/user/profile'
    | '/user/books/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user'
    | '/admin'
    | '/user/books'
    | '/user/loans'
    | '/user/profile'
    | '/user/books/$bookId'
  id:
    | '__root__'
    | '/'
    | '/(protected)/admin'
    | '/(protected)/user'
    | '/(protected)/admin/'
    | '/(protected)/user/books/'
    | '/(protected)/user/loans/'
    | '/(protected)/user/profile/'
    | '/(protected)/user/books/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedAdminRouteRoute: typeof protectedAdminRouteRouteWithChildren
  protectedUserRouteRoute: typeof protectedUserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/user': {
      id: '/(protected)/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof protectedUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/admin': {
      id: '/(protected)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof protectedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/admin/': {
      id: '/(protected)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof protectedAdminIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/user/profile/': {
      id: '/(protected)/user/profile/'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof protectedUserProfileIndexRouteImport
      parentRoute: typeof protectedUserRouteRoute
    }
    '/(protected)/user/loans/': {
      id: '/(protected)/user/loans/'
      path: '/loans'
      fullPath: '/user/loans'
      preLoaderRoute: typeof protectedUserLoansIndexRouteImport
      parentRoute: typeof protectedUserRouteRoute
    }
    '/(protected)/user/books/': {
      id: '/(protected)/user/books/'
      path: '/books'
      fullPath: '/user/books'
      preLoaderRoute: typeof protectedUserBooksIndexRouteImport
      parentRoute: typeof protectedUserRouteRoute
    }
    '/(protected)/user/books/$bookId/': {
      id: '/(protected)/user/books/$bookId/'
      path: '/books/$bookId'
      fullPath: '/user/books/$bookId'
      preLoaderRoute: typeof protectedUserBooksBookIdIndexRouteImport
      parentRoute: typeof protectedUserRouteRoute
    }
  }
}

interface protectedAdminRouteRouteChildren {
  protectedAdminIndexRoute: typeof protectedAdminIndexRoute
}

const protectedAdminRouteRouteChildren: protectedAdminRouteRouteChildren = {
  protectedAdminIndexRoute: protectedAdminIndexRoute,
}

const protectedAdminRouteRouteWithChildren =
  protectedAdminRouteRoute._addFileChildren(protectedAdminRouteRouteChildren)

interface protectedUserRouteRouteChildren {
  protectedUserBooksIndexRoute: typeof protectedUserBooksIndexRoute
  protectedUserLoansIndexRoute: typeof protectedUserLoansIndexRoute
  protectedUserProfileIndexRoute: typeof protectedUserProfileIndexRoute
  protectedUserBooksBookIdIndexRoute: typeof protectedUserBooksBookIdIndexRoute
}

const protectedUserRouteRouteChildren: protectedUserRouteRouteChildren = {
  protectedUserBooksIndexRoute: protectedUserBooksIndexRoute,
  protectedUserLoansIndexRoute: protectedUserLoansIndexRoute,
  protectedUserProfileIndexRoute: protectedUserProfileIndexRoute,
  protectedUserBooksBookIdIndexRoute: protectedUserBooksBookIdIndexRoute,
}

const protectedUserRouteRouteWithChildren =
  protectedUserRouteRoute._addFileChildren(protectedUserRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedAdminRouteRoute: protectedAdminRouteRouteWithChildren,
  protectedUserRouteRoute: protectedUserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
